### ISSUE TITLE
chemex errors when plotting

### ISSUE THREAD

**Issue by viochemist** [gbouvignies/ChemEx#42] opened 2019-03-14 18:36 UTC
Trying to test the example data. Installed chemex with conda and alternatively from cloning and running python setup install, but both have the same error. I'm running on 

Mac OS X El Capitan Ver 10.11.6

Here are the errors. I've never seen anything like this and have no idea where to start debugging:

Plotting Data
=============

File(s):
  * Output/Plots/N15_TROSY_CPMG_@_500_MHz_-_25oC.pdf [.fit, .exp]
2019-03-14 14:32:34.337 python[3987:372627] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fbe1346d410
2019-03-14 14:32:34.338 python[3987:372627] An uncaught exception was raised
2019-03-14 14:32:34.338 python[3987:372627] -[NSApplication _setup:]: unrecognized selector sent to instance 0x7fbe1346d410
2019-03-14 14:32:34.338 python[3987:372627] (
	0   CoreFoundation                      0x00007fff99f7c452 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff96ae6f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff99fe618d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff99eec4c1 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff99eec048 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x0000001a15e1631d TkpInit + 413
	6   libtk8.6.dylib                      0x0000001a15d6e17e Initialize + 2622
	7   _tkinter.cpython-37m-darwin.so      0x0000001a15b96a0f _tkinter_create + 1183
	8   python                              0x0000000100b988b6 _PyMethodDef_RawFastCallKeywords + 230
	9   python                              0x0000000100cd8b47 call_function + 247
	10  python                              0x0000000100cd6684 _PyEval_EvalFrameDefault + 45284
	11  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	12  python                              0x0000000100b97577 _PyFunction_FastCallDict + 231
	13  python                              0x0000000100c1b0b1 slot_tp_init + 193
	14  python                              0x0000000100c25091 type_call + 241
	15  python                              0x0000000100b98283 _PyObject_FastCallKeywords + 179
	16  python                              0x0000000100cd8be4 call_function + 404
	17  python                              0x0000000100cd6778 _PyEval_EvalFrameDefault + 45528
	18  python                              0x0000000100b98078 function_code_fastcall + 120
	19  python                              0x0000000100cd8afe call_function + 174
	20  python                              0x0000000100cd6684 _PyEval_EvalFrameDefault + 45284
	21  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	22  python                              0x0000000100b97577 _PyFunction_FastCallDict + 231
	23  python                              0x0000000100b9b4a2 method_call + 130
	24  python                              0x0000000100b98ef2 PyObject_Call + 130
	25  python                              0x0000000100cd68cf _PyEval_EvalFrameDefault + 45871
	26  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	27  python                              0x0000000100b97577 _PyFunction_FastCallDict + 231
	28  python                              0x0000000100cd68cf _PyEval_EvalFrameDefault + 45871
	29  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	30  python                              0x0000000100b98783 _PyFunction_FastCallKeywords + 195
	31  python                              0x0000000100cd8afe call_function + 174
	32  python                              0x0000000100cd6778 _PyEval_EvalFrameDefault + 45528
	33  python                              0x0000000100b98078 function_code_fastcall + 120
	34  python                              0x0000000100cd8afe call_function + 174
	35  python                              0x0000000100cd65ee _PyEval_EvalFrameDefault + 45134
	36  python                              0x0000000100b98078 function_code_fastcall + 120
	37  python                              0x0000000100cd8afe call_function + 174
	38  python                              0x0000000100cd66bf _PyEval_EvalFrameDefault + 45343
	39  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	40  python                              0x0000000100b98783 _PyFunction_FastCallKeywords + 195
	41  python                              0x0000000100cd8afe call_function + 174
	42  python                              0x0000000100cd6778 _PyEval_EvalFrameDefault + 45528
	43  python                              0x0000000100b98078 function_code_fastcall + 120
	44  python                              0x0000000100cd8afe call_function + 174
	45  python                              0x0000000100cd66bf _PyEval_EvalFrameDefault + 45343
	46  python                              0x0000000100b98078 function_code_fastcall + 120
	47  python                              0x0000000100cd8afe call_function + 174
	48  python                              0x0000000100cd66bf _PyEval_EvalFrameDefault + 45343
	49  python                              0x0000000100b98078 function_code_fastcall + 120
	50  python                              0x0000000100cd8afe call_function + 174
	51  python                              0x0000000100cd6684 _PyEval_EvalFrameDefault + 45284
	52  python                              0x0000000100b98078 function_code_fastcall + 120
	53  python                              0x0000000100cd8afe call_function + 174
	54  python                              0x0000000100cd66bf _PyEval_EvalFrameDefault + 45343
	55  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	56  python                              0x0000000100d2ec40 PyRun_FileExFlags + 256
	57  python                              0x0000000100d2e0b7 PyRun_SimpleFileExFlags + 391
	58  python                              0x0000000100d5a7ec pymain_main + 9564
	59  python                              0x0000000100b6aa9d main + 125
	60  libdyld.dylib                       0x00007fff89c305ad start + 1
)
2019-03-14 14:32:34.339 python[3987:372627] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication _setup:]: unrecognized selector sent to instance 0x7fbe1346d410'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff99f7c452 __exceptionPreprocess + 178
	1   libobjc.A.dylib                     0x00007fff96ae6f7e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff99fe618d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00007fff99eec4c1 ___forwarding___ + 1009
	4   CoreFoundation                      0x00007fff99eec048 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x0000001a15e1631d TkpInit + 413
	6   libtk8.6.dylib                      0x0000001a15d6e17e Initialize + 2622
	7   _tkinter.cpython-37m-darwin.so      0x0000001a15b96a0f _tkinter_create + 1183
	8   python                              0x0000000100b988b6 _PyMethodDef_RawFastCallKeywords + 230
	9   python                              0x0000000100cd8b47 call_function + 247
	10  python                              0x0000000100cd6684 _PyEval_EvalFrameDefault + 45284
	11  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	12  python                              0x0000000100b97577 _PyFunction_FastCallDict + 231
	13  python                              0x0000000100c1b0b1 slot_tp_init + 193
	14  python                              0x0000000100c25091 type_call + 241
	15  python                              0x0000000100b98283 _PyObject_FastCallKeywords + 179
	16  python                              0x0000000100cd8be4 call_function + 404
	17  python                              0x0000000100cd6778 _PyEval_EvalFrameDefault + 45528
	18  python                              0x0000000100b98078 function_code_fastcall + 120
	19  python                              0x0000000100cd8afe call_function + 174
	20  python                              0x0000000100cd6684 _PyEval_EvalFrameDefault + 45284
	21  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	22  python                              0x0000000100b97577 _PyFunction_FastCallDict + 231
	23  python                              0x0000000100b9b4a2 method_call + 130
	24  python                              0x0000000100b98ef2 PyObject_Call + 130
	25  python                              0x0000000100cd68cf _PyEval_EvalFrameDefault + 45871
	26  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	27  python                              0x0000000100b97577 _PyFunction_FastCallDict + 231
	28  python                              0x0000000100cd68cf _PyEval_EvalFrameDefault + 45871
	29  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	30  python                              0x0000000100b98783 _PyFunction_FastCallKeywords + 195
	31  python                              0x0000000100cd8afe call_function + 174
	32  python                              0x0000000100cd6778 _PyEval_EvalFrameDefault + 45528
	33  python                              0x0000000100b98078 function_code_fastcall + 120
	34  python                              0x0000000100cd8afe call_function + 174
	35  python                              0x0000000100cd65ee _PyEval_EvalFrameDefault + 45134
	36  python                              0x0000000100b98078 function_code_fastcall + 120
	37  python                              0x0000000100cd8afe call_function + 174
	38  python                              0x0000000100cd66bf _PyEval_EvalFrameDefault + 45343
	39  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	40  python                              0x0000000100b98783 _PyFunction_FastCallKeywords + 195
	41  python                              0x0000000100cd8afe call_function + 174
	42  python                              0x0000000100cd6778 _PyEval_EvalFrameDefault + 45528
	43  python                              0x0000000100b98078 function_code_fastcall + 120
	44  python                              0x0000000100cd8afe call_function + 174
	45  python                              0x0000000100cd66bf _PyEval_EvalFrameDefault + 45343
	46  python                              0x0000000100b98078 function_code_fastcall + 120
	47  python                              0x0000000100cd8afe call_function + 174
	48  python                              0x0000000100cd66bf _PyEval_EvalFrameDefault + 45343
	49  python                              0x0000000100b98078 function_code_fastcall + 120
	50  python                              0x0000000100cd8afe call_function + 174
	51  python                              0x0000000100cd6684 _PyEval_EvalFrameDefault + 45284
	52  python                              0x0000000100b98078 function_code_fastcall + 120
	53  python                              0x0000000100cd8afe call_function + 174
	54  python                              0x0000000100cd66bf _PyEval_EvalFrameDefault + 45343
	55  python                              0x0000000100cca2d2 _PyEval_EvalCodeWithName + 418
	56  python                              0x0000000100d2ec40 PyRun_FileExFlags + 256
	57  python                              0x0000000100d2e0b7 PyRun_SimpleFileExFlags + 391
	58  python                              0x0000000100d5a7ec pymain_main + 9564
	59  python                              0x0000000100b6aa9d main + 125
	60  libdyld.dylib                       0x00007fff89c305ad start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort

**Comment by reneeotten** [comment] 2019-03-15 13:59
hi Alex, I think it's caused by matplotlib and the backend you are using; from what I've read it seems related to the fact that conda doesn't install a framework build of Python... 

Anyway, if you just open Python and do ```import matplotlib``` does that work or it already throws that error. If the import works, please check which backend you are using ```matplotlib.get_backend()``` (at least for me using the "TkAgg" backend works). It might read that information from a left-over configuration file ```~/.matplotlib/matplotlibrc``` so you should also check what it says in there.

Hope that helps to give you a starting point....

**Comment by reneeotten** [comment] 2019-03-15 14:19
never mind, I actually get the same error as you when using conda... (see [here]( https://github.com/conda-forge/matplotlib-feedstock/issues/200) for an upstream bug report). I don't know yet how to fix this right now in chemex until it's handled upstream, but we can certainly investigate a bit more - just not now ;)

**Comment by gbouvignies** [comment] 2019-03-15 14:54
Hi Alex,

This is an issue with `matplotlib=3`, which seems to misbehave with the conda version of `python` on MacOS. This is documented [here](https://stackoverflow.com/questions/54282402/error-when-running-matplotlib-in-anaconda) and [there](https://github.com/matplotlib/matplotlib/issues/13096).

Temporary fixes are either:
- `conda install matplotlib=2`
- use of `pythonw` instead of `python` (`conda install pythonw`)
    `pythonw -m chemex fit -e...` instead of `chemex fit -e...`
- add `backend: macosx` to `~/.matplotlibrc`

Hopefully it will be fixed soon. On our side, not sure what should be done, beside enforcing the install of `matplotlib=2` via the dependencies of the package or the use of `pythonw` by making `chemex` a `gui_scripts` and not a `console_scripts` as it is now defined in the `setup.py`. I haven't tested the latter yet.

**Comment by gbouvignies** [comment] 2021-07-22 13:19
Fixed on Matplotlib side.

**Closed by gbouvignies** 2021-07-22 13:19 UTC
